language: node_js
node_js:
  - 11.6.0
cache: npm

# before_install:
#   - git pull origin gh-pages

install:
  - npm install
  # - npm install cypress
  # - npm install --save-dev cypress cypress-cucumber-preprocessor

script:
  - docker pull michelleamesquita/cypress-ci-reports
  - docker run -v /etc/hosts:/etc/hosts michelleamesquita/cypress-ci-reports
  #- docker run -v $PWD/:/app/report/ michelleamesquita/cypress-ci-reports

after_success:
  - git init
  - git config user.name "Travis CI"
  - git config user.email "travis@travis.org"
  - git add reports/cucumber_report.html
  - git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://michelleamesquita:${GITHUB_API_KEY}@${GH_REF}" HEAD:gh-pages
  # - git push --quiet "https://michelleamesquita:${GITHUB_API_KEY}@${GH_REF}" HEAD:main
  #- git push --force --quiet "https://michelleamesquita:${GITHUB_API_KEY}@${GH_REF}" main:gh-pages > /dev/null 2>&1
  

  #- docker run michelleamesquita/cypress-ci-reports cat /app/report/cucumber_report.html > cucumber_report.html
  #- docker run michelleamesquita/cypress-ci-report cat /app/public/index.html > index.html
  
  # - npm run test:sucess
  # - npm run report:merge 
  # - npm run report:generate
