language: node_js
node_js:
  - 11.6.0
cache: npm

install:
  - npm install
  # - npm install cypress
  # - npm install --save-dev cypress cypress-cucumber-preprocessor

script:
  - docker pull michelleamesquita/cypress-ci-reports
  - docker run -v $PWD/:/app/report/ michelleamesquita/cypress-ci-reports
  - git init
  - git config user.name "Travis CI"
  - git config user.email "michelleamesquita@gmail.com"
  - git add .
  - git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1


  #- docker run michelleamesquita/cypress-ci-reports cat /app/report/cucumber_report.html > cucumber_report.html
  #- docker run michelleamesquita/cypress-ci-report cat /app/public/index.html > index.html
  
  # - npm run test:sucess
  # - npm run report:merge 
  # - npm run report:generate

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master 
