language: node_js
node_js:
  - 11.6.0
cache: npm

install:
  - npm install
  - npm install cypress
  - npm install --save-dev cypress cypress-cucumber-preprocessor

script:
  - npm run test:sucess
  - npm run report:merge 
  - npm run report:generate

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master 
