language: node_js
node_js:
  - 11.6.0
cache: npm

# before_install:
#   - git pull origin gh-pages

install:
  - npm install
  # - npm install cypress
  # - npm install --save-dev cypress cypress-cucumber-preprocessor

script:
  - docker pull michelleamesquita/cypress-ci-reports
  #- docker run -v /etc/hosts:/etc/hosts michelleamesquita/cypress-ci-reports
  #- ls
  - docker run -v $PWD/:/app/report/ michelleamesquita/cypress-ci-reports
  #- docker run -v $PWD/:/app/report/ michelleamesquita/cypress-ci-reports2
  
# after_success:

after_script:

  - ls  
  - chmod +x final_report.sh
  - . final_report.sh
  - chmod +x telegram.sh
  - . telegram.sh
  
  - git init
  - git config user.name "Travis CI"
  - git config user.email "travis@travis.org"
  #- git add /report/cucumber_report.html
  - git add cucumber_report.html
  - git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://michelleamesquita:${GITHUB_API_KEY}@${GH_REF}" HEAD:gh-pages
  - echo $RESULT
  - bash ./telegram.sh
#   - if [ $RESULT -le 100 ]; then travis_terminate 1; fi


  
# after_script:
#   - bash ./telegram_notification.sh
  # - git push --quiet "https://michelleamesquita:${GITHUB_API_KEY}@${GH_REF}" HEAD:main
  #- git push --force --quiet "https://michelleamesquita:${GITHUB_API_KEY}@${GH_REF}" main:gh-pages > /dev/null 2>&1
  

  #- docker run michelleamesquita/cypress-ci-reports cat /app/report/cucumber_report.html > cucumber_report.html
  #- docker run michelleamesquita/cypress-ci-report cat /app/public/index.html > index.html
  
  # - npm run test:sucess
  # - npm run report:merge 
  # - npm run report:generate
